version: '3.8'

services:
  db:
    image: postgres:13
    container_name: antiplagiat_db
    environment:
      POSTGRES_DB: antiplagiat
      POSTGRES_USER: antiplagiat
      POSTGRES_PASSWORD: antiplagiat
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  file-storing-service:
    build:
      context: ./file-storing-service
      dockerfile: Dockerfile
    container_name: file_storing_service
    ports:
      - "8080:8080"
    expose:
      - "8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/antiplagiat
      SPRING_DATASOURCE_USERNAME: antiplagiat
      SPRING_DATASOURCE_PASSWORD: antiplagiat
      SERVER_PORT: 8080
    volumes:
      - file_uploads:/app/uploads

  file-analysis-service:
    build:
      context: ./file-analysis-service
      dockerfile: Dockerfile
    container_name: file_analysis_service
    ports:
      - "8081:8081"
    expose:
      - "8081"
    depends_on:
      - db
      - file-storing-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/antiplagiat
      SPRING_DATASOURCE_USERNAME: antiplagiat
      SPRING_DATASOURCE_PASSWORD: antiplagiat
      FILE_STORAGE_SERVICE_URL: http://file-storing-service:8080
      SERVER_PORT: 8081

volumes:
  postgres_data:
  file_uploads: